---
- hosts: localhost
  roles:
  - {role: base}
  - {role: zsh}
  - {role: vim}
  - {role: mononoki}
  - {role: gui}
  - {role: tearingfix}
  - {role: throttled}
  - {role: slock}
  - {role: ufw}
  - {role: tlp}
  - {role: emacs}
  - {role: bbswitch}
  - {role: intellij}
