---
- name: Install graphical packages
  become: yes
  xbps: 
    name: "{{graphic_package_list}}"
    state: latest
    update_cache: yes
  register: installation

- name: Clone mons
  git:
    repo: https://github.com/Ventto/mons
    dest: "{{src_home}}/mons"
  register: mons

- name: Install mons
  become: yes
  make:
    chdir: "{{src_home}}/mons"
    target: install
  when: mons.changed

- name: Clone lemonbar
  git:
    repo: https://github.com/drscream/bar
    dest: "{{src_home}}/lemonbar"
  register: lemonbar

- name: Install lemonbar
  become: yes
  make:
    chdir: "{{src_home}}/lemonbar"
    target: install
  when: lemonbar.changed

- name: Create config dirs
  file:
    path: "{{dotfiles_user_home}}/.config/{{item}}"
    state: directory
  with_items:
    - "alacritty"
    - "sxhkd"
    - "bspwm"
    - "rofi"

- name: Configure sxhkd
  file:
    src: "{{role_path}}/files/config/sxhkd/sxhkdrc"
    dest: "{{dotfiles_user_home}}/.config/sxhkd/sxhkdrc"
    state: link
    force: yes
 
- name: Configure bspwm and bar
  file:
    src: "{{role_path}}/files/config/bspwm/*"
    dest: "{{dotfiles_user_home}}/.config/bspwm"
    state: link
    force: yes

- name: Configure terminal
  file:
    src: "{{role_path}}/files/config/alacritty/alacritty.yml"
    dest: "{{dotfiles_user_home}}/.config/alacritty/alacritty.yml"
    state: link
    force: yes

- name: Configure rofi
  file:
    src: "{{role_path}}/files/config/rofi/*"
    dest: "{{dotfiles_user_home}}/.config/rofi"
    state: link
    force: yes

- name: Link xinitrc
  file:
    src: "{{role_path}}/files/xinitrc"
    dest: "{{dotfiles_user_home}}/.xinitrc"
    state: link
    force: yes
