---
- name: Install graphical packages
  become: yes
  pacman: 
    name: "{{graphic_package_list}}"
    state: latest
    update_cache: yes
  register: installation

- name: Create config dirs
  file:
    path: "{{dotfiles_user_home}}/.config/{{item}}"
    state: directory
  with_items:
    - "fontconfig"

- name: Configure fonts
  file:
    src: "{{role_path}}/files/config/fontconfig/fonts.conf"
    dest: "{{dotfiles_user_home}}/.config/fontconfig/fonts.conf"
    state: link
    force: yes

- name: Enable gdm
  become: yes
  service:
    name: gdm
    enabled: yes
