---
- name: Install graphical packages
  become: yes
  apt: 
    name: "{{graphic_package_list}}"
    state: latest
    update_cache: yes
  register: installation

- name: Clone mons
  git:
    repo: https://github.com/Ventto/mons
    dest: "{{src_home}}/mons"
  register: mons

- name: Install mons
  become: yes
  make:
    chdir: "{{src_home}}/mons"
    target: install
  when: mons.changed

- name: Create config dirs
  file:
    path: "{{dotfiles_user_home}}/.config/{{item}}"
    state: directory
  with_items:
    - "sxhkd"
    - "bspwm"

- name: Configure sxhkd
  file:
    src: "{{role_path}}/files/config/sxhkd/sxhkdrc"
    dest: "{{dotfiles_user_home}}/.config/sxhkd/sxhkdrc"
    state: link
    force: yes
 
- name: Configure bspwm
  file:
    src: "{{role_path}}/files/config/bspwm/*"
    dest: "{{dotfiles_user_home}}/.config/bspwm"
    state: link
    force: yes

- name: Link xinitrc
  file:
    src: "{{role_path}}/files/xinitrc"
    dest: "{{dotfiles_user_home}}/.xinitrc"
    state: link
    force: yes
