---
- name: Install base packages
  become: yes
  pacman: 
    name: "{{base_package_list}}"
    state: latest
    update_cache: yes

- name: Update git config
  template:
    src: "gitconfig.j2"
    dest: "{{dotfiles_user_home}}/.gitconfig"

- name: Create user directories
  file:
    path: "{{dotfiles_user_home}}/{{item}}"
    state: directory
  with_items:
    - ".local"
    - ".local/temp"
    - ".local/pub"
    - "dev"
    - "src"
    - "dl"
    - "doc"
    - "doc/books"
    - "doc/pres"
    - "mus"
    - "pic/vid"
    - ".config"

- name: Configure user dirs
  file:
    src: "{{ role_path }}/files/config/user-dirs.dirs"
    dest: "{{ dotfiles_user_home }}/.config/user-dirs.dirs"
    state: link
    force: yes
  register: userdirs

- name: Update user-dirs
  command: xdg-user-dirs-update
  when: userdirs.changed
