---
- name: Install bbswitch
  become: yes
  xbps:
    name: bbswitch
    state: latest
    update_cache: yes

- name: Create modules-load.d
  become: yes
  file:
    dest: /etc/modules-load.d
    state: directory

- name: Copy modprobe config
  become: yes
  copy:
    src: bbswitch.conf
    dest: /etc/modprobe.d/bbswitch.conf
    force: yes

- name: Start on boot
  become: yes
  copy:
    src: load.conf
    dest: /etc/modules-load.d/bbswitch.conf
    force: yes
