---
- name: Install graphical packages
  become: yes
  pacman: 
    name: "{{graphic_package_list}}"
    state: latest
    update_cache: yes
  register: installation

- name: Clone dwm
  git:
    repo: https://github.com/atred/dwm
    dest: "{{dev_home}}/dwm"
    version: "{{screen_size}}"
  register: cloning
  when: installation is success

- name: Build dwm
  make:
    chdir: "{{dev_home}}/dwm"
  register: building
  when: cloning.changed

- name: Install dwm
  become: yes
  make:
    chdir: "{{dev_home}}/dwm"
    target: install
  when: building.changed

- name: Clean dwm directory
  make:
    chdir: "{{dev_home}}/dwm"
    target: clean
  when: cloning.changed

- name: Clone mons
  git:
    repo: https://github.com/Ventto/mons
    dest: "{{dev_home}}/mons"
  register: mons

- name: Install mons
  become: yes
  make:
    chdir: "{{dev_home}}/mons"
    target: install
  when: mons.changed

- name: Clean mons directory
  make:
    chdir: "{{dev_home}}/mons"
    target: clean
  when: mons.changed

- name: Create sxhkd dir
  file:
      path: "{{dotfiles_user_home}}/.config/sxhkd"
      state: directory

- name: Configure sxhkd
  file:
    src: "{{role_path}}/files/config/sxhkd/sxhkdrc"
    dest: "{{dotfiles_user_home}}/.config/sxhkd/sxhkdrc"
    state: link
    force: yes

- name: Link xinitrc
  file:
    src: "{{role_path}}/files/xinitrc"
    dest: "{{dotfiles_user_home}}/.xinitrc"
    state: link
    force: yes
