---
- name: Install slock
  become: yes
  pacman:
    name: slock
    state: latest
    update_cache: yes

- name: Create slock service
  become: yes
  template:
    src: "lock.j2"
    dest: "/etc/systemd/system/lock.service"
  register: creation

- name: Enable slock service
  become: yes
  command: systemctl enable lock.service
  when: creation is changed
