---
- name: Install zsh
  become: yes
  pacman: 
    name: zsh
    state: latest
    update_cache: yes
  register: installation

- name: Check existing .zshrc
  stat: path="{{dotfiles_user_home}}/.zshrc"
  when: installation is success
  register: zshrc_stat

- name: Backup .zshrc
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{dotfiles_user_home}}/.oh-my-zsh"
  when: installation is success
  register: cloning

- name: Build new .zshrc
  copy:
    src: "{{dotfiles_user_home}}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{dotfiles_user_home}}/.zshrc"
  when: cloning is success

- name: Change user shell
  become: yes
  user:
    name: andrew
    shell: /bin/zsh
  when: cloning is success
