---
- name: Install zsh
  become: yes
  xbps: 
    name: zsh
    state: latest
    update_cache: yes
  register: installation

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{dotfiles_user_home}}/.oh-my-zsh"
  when: installation is success

- name: Create new .zshrc
  file:
    src: "{{role_path}}/files/zshrc"
    dest: "{{dotfiles_user_home}}/.zshrc"
    state: link
    force: yes
  when: installation is success

- name: Create new .zprofile
  file:
    src: "{{role_path}}/files/zprofile"
    dest: "{{dotfiles_user_home}}/.zprofile"
    state: link
    force: yes
  when: installation is success

- name: Change user shell
  become: yes
  user:
    name: andrew
    shell: /bin/zsh
  when: installation is success
