---
- name: Create vim config dir
  file:
    path: "{{ dotfiles_user_home }}/.config/nvim"
    state: directory

- name: Link vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: "{{ dotfiles_user_home }}/.config/nvim/init.vim"
    state: link
    force: yes
