---
- name: Link vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: "{{ dotfiles_user_home }}/.vimrc"
    state: link
    force: yes
  register: vimrc

- name: Install vim plugins
  command: vim -E -s -c "source ~/.vimrc" -c PlugInstall -c qa
  register: pluginsInstalled
  when: vimrc.changed
