---
- name: Create font dir
  become: yes
  file:
    path: "/usr/share/fonts"
    state: directory

- name: Checking for mononoki
  stat:
    path: /usr/share/fonts/mononoki-Regular.ttf
  register: monoinst

- name: Install mononoki
  become: yes
  unarchive:
    src: https://github.com/madmalik/mononoki/releases/download/1.2/mononoki.zip
    dest: /usr/share/fonts
    remote_src: yes
  when: not monoinst.stat.exists
  register: monodl

- name: Reload font cache
  command: fc-cache -fv
  when: monodl is changed
