---
- name: Link vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: "{{ dotfiles_user_home }}/.vimrc"
    state: link
    force: yes
  register: vimrc

- name: Run :PlugInstall
  command: vim +'PlugInstall --sync' +qa
  when: vimrc.changed
