---
- name: Install emacs
  become: yes
  pacman:
    name: emacs
    state: latest
    update_cache: yes

- name: Clone .emacs.d
  git:
    repo: https://github.com/atred/.emacs.d.git
    dest: "{{dotfiles_user_home}}/.emacs.d"
